// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/get-my-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in Repview user's profile record (display name, avatar).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("profiles").select("display_name, avatar_url, created_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const profile = { email: ctx.getUserEmail(), ...data ?? {} };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: { profile }
    };
  }
});

// src/lib/mcp/tools/list-accounts.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^4.4.3";

// src/data/demo-data.ts
var accounts = [
  { id: "a1", name: "Henderson Architecture Group", type: "Architect", territory: "Northeast", owner: "Mike Torres", city: "Boston", state: "MA", phone: "(617) 555-0142", website: "hendersonarch.com", lastActivity: "2026-03-27", contactCount: 4, oppCount: 6 },
  { id: "a2", name: "Summit Roofing Contractors", type: "Roofing Contractor", territory: "Northeast", owner: "Mike Torres", city: "Hartford", state: "CT", phone: "(860) 555-0198", website: "summitroofing.com", lastActivity: "2026-03-28", contactCount: 3, oppCount: 8 },
  { id: "a3", name: "Beacon Building Products", type: "Distributor", territory: "Northeast", owner: "Sarah Chen", city: "New York", state: "NY", phone: "(212) 555-0234", website: "becn.com", lastActivity: "2026-03-25", contactCount: 5, oppCount: 12 },
  { id: "a4", name: "Patriot Development Corp", type: "Developer", territory: "Mid-Atlantic", owner: "Sarah Chen", city: "Philadelphia", state: "PA", phone: "(215) 555-0167", website: "patriotdev.com", lastActivity: "2026-03-20", contactCount: 2, oppCount: 3 },
  { id: "a5", name: "Atlantic Waterproofing Inc", type: "Waterproofing Contractor", territory: "Mid-Atlantic", owner: "James Wright", city: "Baltimore", state: "MD", phone: "(410) 555-0189", website: "atlanticwp.com", lastActivity: "2026-03-26", contactCount: 3, oppCount: 5 },
  { id: "a6", name: "Northstar Consulting Engineers", type: "Consultant", territory: "Northeast", owner: "James Wright", city: "Providence", state: "RI", phone: "(401) 555-0145", website: "northstarce.com", lastActivity: "2026-03-22", contactCount: 2, oppCount: 4 },
  { id: "a7", name: "Metro General Contractors", type: "General Contractor", territory: "Northeast", owner: "Mike Torres", city: "Newark", state: "NJ", phone: "(973) 555-0211", website: "metrogc.com", lastActivity: "2026-03-24", contactCount: 4, oppCount: 7 },
  { id: "a8", name: "Skyline Glass & Glazing", type: "Glazing Contractor", territory: "Mid-Atlantic", owner: "Sarah Chen", city: "Washington", state: "DC", phone: "(202) 555-0178", website: "skylineglazing.com", lastActivity: "2026-03-18", contactCount: 2, oppCount: 3 },
  { id: "a9", name: "Greenfield University", type: "Building Owner", territory: "Northeast", owner: "Mike Torres", city: "Worcester", state: "MA", phone: "(508) 555-0299", website: "greenfieldu.edu", lastActivity: "2026-03-15", contactCount: 3, oppCount: 2 },
  { id: "a10", name: "Capital Facilities Group", type: "Facilities Owner", territory: "Mid-Atlantic", owner: "James Wright", city: "Richmond", state: "VA", phone: "(804) 555-0122", website: "capitalfacilities.com", lastActivity: "2026-03-19", contactCount: 2, oppCount: 4 }
];
var contacts = [
  { id: "c1", name: "Robert Henderson", title: "Principal", accountId: "a1", accountName: "Henderson Architecture Group", email: "rhenderson@hendersonarch.com", phone: "(617) 555-0142", role: "Decision Maker", influenceLevel: "High", lastActivity: "2026-03-27" },
  { id: "c2", name: "Lisa Chang", title: "Project Architect", accountId: "a1", accountName: "Henderson Architecture Group", email: "lchang@hendersonarch.com", phone: "(617) 555-0143", role: "Specifier", influenceLevel: "High", lastActivity: "2026-03-25" },
  { id: "c3", name: "Tom Sullivan", title: "President", accountId: "a2", accountName: "Summit Roofing Contractors", email: "tsullivan@summitroofing.com", phone: "(860) 555-0198", role: "Decision Maker", influenceLevel: "High", lastActivity: "2026-03-28" },
  { id: "c4", name: "Maria Gonzalez", title: "Estimator", accountId: "a2", accountName: "Summit Roofing Contractors", email: "mgonzalez@summitroofing.com", phone: "(860) 555-0199", role: "Evaluator", influenceLevel: "Medium", lastActivity: "2026-03-26" },
  { id: "c5", name: "David Park", title: "Branch Manager", accountId: "a3", accountName: "Beacon Building Products", email: "dpark@becn.com", phone: "(212) 555-0234", role: "Decision Maker", influenceLevel: "High", lastActivity: "2026-03-25" },
  { id: "c6", name: "Jennifer Okafor", title: "VP Development", accountId: "a4", accountName: "Patriot Development Corp", email: "jokafor@patriotdev.com", phone: "(215) 555-0167", role: "Champion", influenceLevel: "High", lastActivity: "2026-03-20" },
  { id: "c7", name: "Kevin Walsh", title: "Operations Manager", accountId: "a5", accountName: "Atlantic Waterproofing Inc", email: "kwalsh@atlanticwp.com", phone: "(410) 555-0189", role: "Technical Buyer", influenceLevel: "Medium", lastActivity: "2026-03-26" },
  { id: "c8", name: "Amy Nguyen", title: "Senior Engineer", accountId: "a6", accountName: "Northstar Consulting Engineers", email: "anguyen@northstarce.com", phone: "(401) 555-0145", role: "Specifier", influenceLevel: "High", lastActivity: "2026-03-22" },
  { id: "c9", name: "Brian Miller", title: "Project Manager", accountId: "a7", accountName: "Metro General Contractors", email: "bmiller@metrogc.com", phone: "(973) 555-0211", role: "Evaluator", influenceLevel: "Medium", lastActivity: "2026-03-24" },
  { id: "c10", name: "Sandra Hayes", title: "Director of Facilities", accountId: "a9", accountName: "Greenfield University", email: "shayes@greenfieldu.edu", phone: "(508) 555-0299", role: "Decision Maker", influenceLevel: "High", lastActivity: "2026-03-15" }
];
var opportunities = [
  { id: "o1", name: "City Center Tower - Roof Replacement", accountName: "Summit Roofing Contractors", stage: "Bid", value: 485e3, probability: 60, closeDate: "2026-05-15", manufacturerLine: "Carlisle SynTec", productCategory: "Roofing", territory: "Northeast", owner: "Mike Torres", projectName: "City Center Tower", bidDate: "2026-04-10", source: "Existing Relationship", forecastStatus: "Open" },
  { id: "o2", name: "Harbor Medical Campus - Skylights", accountName: "Henderson Architecture Group", stage: "Specification", value: 32e4, probability: 40, closeDate: "2026-07-20", manufacturerLine: "VELUX Skylights", productCategory: "Skylights", territory: "Northeast", owner: "Mike Torres", projectName: "Harbor Medical Campus", source: "Architect Spec", forecastStatus: "Open" },
  { id: "o3", name: "Patriot Plaza Ph2 - Waterproofing", accountName: "Patriot Development Corp", stage: "Bid", value: 275e3, probability: 70, closeDate: "2026-04-30", manufacturerLine: "Tremco Roofing", productCategory: "Waterproofing", territory: "Mid-Atlantic", owner: "Sarah Chen", projectName: "Patriot Plaza Phase 2", bidDate: "2026-03-28", source: "Developer Direct", forecastStatus: "Open" },
  { id: "o4", name: "Greenfield Science Hall - Insulation", accountName: "Greenfield University", stage: "Specification", value: 142e3, probability: 30, closeDate: "2026-08-15", manufacturerLine: "Hunter Panels", productCategory: "Insulation", territory: "Northeast", owner: "Mike Torres", projectName: "Greenfield Science Hall", source: "Owner Direct", forecastStatus: "Open" },
  { id: "o5", name: "Metro Office Complex - Full Envelope", accountName: "Metro General Contractors", stage: "Specified", value: 89e4, probability: 75, closeDate: "2026-04-20", manufacturerLine: "Carlisle SynTec", productCategory: "Roofing", territory: "Northeast", owner: "Mike Torres", projectName: "Metro Office Complex", source: "GC Bid Request", forecastStatus: "Open" },
  { id: "o6", name: "Capital Center Reroof", accountName: "Capital Facilities Group", stage: "Awarded", value: 356e3, probability: 95, closeDate: "2026-04-05", manufacturerLine: "Soprema", productCategory: "Roofing", territory: "Mid-Atlantic", owner: "James Wright", source: "Existing Relationship", forecastStatus: "Closed Won" },
  { id: "o7", name: "Beacon Distribution Center - Cladding", accountName: "Beacon Building Products", stage: "Prospect", value: 21e4, probability: 15, closeDate: "2026-09-30", manufacturerLine: "Kingspan Insulation", productCategory: "Cladding", territory: "Northeast", owner: "Sarah Chen", source: "Cold Call", forecastStatus: "Open" },
  { id: "o8", name: "Atlantic WP - Cover Board Supply", accountName: "Atlantic Waterproofing Inc", stage: "Bid", value: 95e3, probability: 55, closeDate: "2026-05-01", manufacturerLine: "Georgia-Pacific DensDeck", productCategory: "Cover Boards", territory: "Mid-Atlantic", owner: "James Wright", source: "Contractor Direct", forecastStatus: "Open" },
  { id: "o9", name: "Skyline HQ Curtainwall Skylights", accountName: "Skyline Glass & Glazing", stage: "Specification", value: 42e4, probability: 35, closeDate: "2026-08-01", manufacturerLine: "VELUX Skylights", productCategory: "Skylights", territory: "Mid-Atlantic", owner: "Sarah Chen", source: "Architect Referral", forecastStatus: "Open" },
  { id: "o10", name: "Harbor Medical - Roofing", accountName: "Summit Roofing Contractors", stage: "Awarded", value: 615e3, probability: 100, closeDate: "2026-01-15", manufacturerLine: "Carlisle SynTec", productCategory: "Roofing", territory: "Northeast", owner: "Mike Torres", projectName: "Harbor Medical Campus", source: "Existing Relationship", forecastStatus: "Closed Won" },
  { id: "o11", name: "Providence Library Reroof", accountName: "Northstar Consulting Engineers", stage: "Prospect", value: 188e3, probability: 10, closeDate: "2026-02-28", manufacturerLine: "Tremco Roofing", productCategory: "Roofing", territory: "Northeast", owner: "James Wright", source: "Consultant Spec", forecastStatus: "Open" },
  { id: "o12", name: "Patriot Plaza Ph1 - Insulation", accountName: "Patriot Development Corp", stage: "Awarded", value: 198e3, probability: 100, closeDate: "2025-11-20", manufacturerLine: "Kingspan Insulation", productCategory: "Insulation", territory: "Mid-Atlantic", owner: "Sarah Chen", source: "Developer Direct", forecastStatus: "Closed Won" }
];
var projects = [
  { id: "p1", name: "City Center Tower", address: "200 Main Street", city: "Hartford", state: "CT", type: "Commercial Office", status: "Bidding", sqft: 85e3, bidDate: "2026-04-10", owner: "City Center LLC", architect: "Henderson Architecture Group", contractors: [{ name: "Metro General Contractors", isPrimary: true }, { name: "Atlantic Waterproofing Inc" }], oppCount: 2 },
  { id: "p2", name: "Harbor Medical Campus", address: "45 Harbor Blvd", city: "Boston", state: "MA", type: "Healthcare", status: "Design", sqft: 12e4, bidDate: "2026-06-15", owner: "Harbor Health Systems", architect: "Henderson Architecture Group", contractors: [], oppCount: 3 },
  { id: "p3", name: "Patriot Plaza Phase 2", address: "1600 Market St", city: "Philadelphia", state: "PA", type: "Mixed Use", status: "Bidding", sqft: 65e3, bidDate: "2026-03-28", owner: "Patriot Development Corp", architect: "KPF Associates", contractors: [{ name: "Turner Construction", isPrimary: true }], oppCount: 2 },
  { id: "p4", name: "Greenfield Science Hall", address: "100 University Drive", city: "Worcester", state: "MA", type: "Education", status: "Pre-Design", sqft: 42e3, bidDate: "2026-07-01", owner: "Greenfield University", architect: "Payette", contractors: [], oppCount: 1 },
  { id: "p5", name: "Metro Office Complex", address: "500 Broad St", city: "Newark", state: "NJ", type: "Commercial Office", status: "Complete", sqft: 175e3, bidDate: "2026-02-15", owner: "Metro Properties LLC", architect: "Gensler", contractors: [{ name: "Metro General Contractors", isPrimary: true }, { name: "Whiting-Turner" }], oppCount: 1 },
  { id: "p6", name: "Capital Center", address: "800 Capitol Ave", city: "Richmond", state: "VA", type: "Government", status: "Bidding", sqft: 55e3, bidDate: "2026-01-10", owner: "State of Virginia", architect: "Clark Nexsen", contractors: [{ name: "Whiting-Turner", isPrimary: true }], oppCount: 1 }
];
var quotes = [
  { id: "q1", number: "QT-2026-0042", oppName: "City Center Tower - Roof Replacement", accountName: "Summit Roofing Contractors", manufacturerLine: "Carlisle SynTec", status: "Submitted", total: 485e3, created: "2026-03-15", expires: "2026-04-15", version: 2 },
  { id: "q2", number: "QT-2026-0041", oppName: "Atlantic WP - Cover Board Supply", accountName: "Atlantic Waterproofing Inc", manufacturerLine: "Georgia-Pacific DensDeck", status: "Submitted", total: 95e3, created: "2026-03-12", expires: "2026-04-12", version: 1 },
  { id: "q3", number: "QT-2026-0040", oppName: "Patriot Plaza Ph2 - Waterproofing", accountName: "Patriot Development Corp", manufacturerLine: "Tremco Roofing", status: "Accepted", total: 275e3, created: "2026-03-01", expires: "2026-04-01", version: 3 },
  { id: "q4", number: "QT-2026-0039", oppName: "Metro Office Complex - Full Envelope", accountName: "Metro General Contractors", manufacturerLine: "Carlisle SynTec", status: "Internal Review", total: 89e4, created: "2026-03-20", expires: "2026-04-20", version: 1 },
  { id: "q5", number: "QT-2026-0038", oppName: "Greenfield Science Hall - Insulation", accountName: "Greenfield University", manufacturerLine: "Hunter Panels", status: "Draft", total: 142e3, created: "2026-03-22", expires: "2026-04-22", version: 1 },
  { id: "q6", number: "QT-2025-0187", oppName: "Harbor Medical - Roofing", accountName: "Summit Roofing Contractors", manufacturerLine: "Carlisle SynTec", status: "Accepted", total: 615e3, created: "2025-10-15", expires: "2025-11-15", version: 4 }
];
var orders = [
  { id: "ord1", orderNumber: "ORD-2026-0018", mfgOrderNumber: "CST-882341", accountName: "Summit Roofing Contractors", manufacturerLine: "Carlisle SynTec", status: "Booked", total: 615e3, orderDate: "2026-01-20", expectedShip: "2026-04-10", project: "Harbor Medical Campus", orderStage: "In Production", opportunityId: "o10" },
  { id: "ord2", orderNumber: "ORD-2026-0019", mfgOrderNumber: "SOP-443211", accountName: "Capital Facilities Group", manufacturerLine: "Soprema", status: "Pending", total: 356e3, orderDate: "2026-03-28", expectedShip: "2026-05-15", project: "Capital Center", orderStage: "Entered", opportunityId: "o6" },
  { id: "ord3", orderNumber: "ORD-2026-0017", mfgOrderNumber: "TRM-991287", accountName: "Patriot Development Corp", manufacturerLine: "Tremco Roofing", status: "Booked", total: 275e3, orderDate: "2026-03-25", expectedShip: "2026-05-01", project: "Patriot Plaza Phase 2", orderStage: "Acknowledged" },
  { id: "ord4", orderNumber: "ORD-2025-0145", mfgOrderNumber: "KSP-228834", accountName: "Patriot Development Corp", manufacturerLine: "Kingspan Insulation", status: "Shipped", total: 198e3, orderDate: "2025-09-15", expectedShip: "2025-10-30", project: "Patriot Plaza Phase 1", orderStage: "Complete", opportunityId: "o12" },
  { id: "ord5", orderNumber: "ORD-2025-0152", mfgOrderNumber: "CST-871290", accountName: "Metro General Contractors", manufacturerLine: "Carlisle SynTec", status: "Shipped", total: 445e3, orderDate: "2025-12-10", expectedShip: "2026-03-25", project: "Metro Office Complex", orderStage: "Shipped" }
];
var tasks = [
  { id: "t1", title: "Follow up on City Center bid results", dueDate: "2026-04-11", priority: "High", status: "Open", linkedTo: "City Center Tower - Roof Replacement", owner: "Mike Torres" },
  { id: "t2", title: "Send revised Harbor Medical skylight layout", dueDate: "2026-03-31", priority: "High", status: "In Progress", linkedTo: "Harbor Medical Campus - Skylights", owner: "Mike Torres" },
  { id: "t3", title: "Prepare Greenfield budget pricing", dueDate: "2026-04-05", priority: "Medium", status: "Open", linkedTo: "Greenfield Science Hall - Insulation", owner: "Mike Torres" },
  { id: "t4", title: "Schedule Capital Center pre-install meeting", dueDate: "2026-04-01", priority: "Medium", status: "Open", linkedTo: "Capital Center Reroof", owner: "James Wright" },
  { id: "t5", title: "Submit Kingspan samples to Beacon", dueDate: "2026-04-03", priority: "Low", status: "Open", linkedTo: "Beacon Distribution Center - Cladding", owner: "Sarah Chen" },
  { id: "t6", title: "Update Metro Office Complex quote v2", dueDate: "2026-03-30", priority: "High", status: "In Progress", linkedTo: "Metro Office Complex - Full Envelope", owner: "Mike Torres" }
];
var dashboardStats = {
  pipelineValue: 3195e3,
  weightedForecast: 1842750,
  openOpps: 9,
  wonThisYear: 813e3,
  quotesOutstanding: 4,
  ordersInProgress: 3,
  activitiesThisMonth: 24,
  avgDealSize: 355e3
};
var pipelineByStage = [
  { stage: "Lead", value: 21e4, count: 1 },
  { stage: "Spec Influence", value: 74e4, count: 2 },
  { stage: "Budget Pricing", value: 142e3, count: 1 },
  { stage: "Quoted", value: 58e4, count: 2 },
  { stage: "Bid Submitted", value: 275e3, count: 1 },
  { stage: "Negotiation", value: 89e4, count: 1 },
  { stage: "Awarded", value: 356e3, count: 1 }
];
var revenueByLine = [
  { name: "Carlisle SynTec", value: 199e4 },
  { name: "VELUX Skylights", value: 74e4 },
  { name: "Tremco Roofing", value: 463e3 },
  { name: "Soprema", value: 356e3 },
  { name: "Kingspan", value: 408e3 },
  { name: "Hunter Panels", value: 142e3 },
  { name: "GP DensDeck", value: 95e3 }
];
var forecastByRep = [
  { rep: "Mike Torres", commit: 89e4, bestCase: 1475e3, upside: 1827e3 },
  { rep: "Sarah Chen", commit: 275e3, bestCase: 695e3, upside: 905e3 },
  { rep: "James Wright", commit: 356e3, bestCase: 451e3, upside: 639e3 }
];

// src/lib/mcp/tools/list-accounts.ts
var list_accounts_default = defineTool2({
  name: "list_accounts",
  title: "List accounts",
  description: "List CRM accounts (architects, contractors, owners, distributors) with optional filtering by name, type, or territory.",
  inputSchema: {
    search: z.string().optional().describe("Case-insensitive match on account name or city."),
    type: z.string().optional().describe("Account type, e.g. Architect, General Contractor, Distributor."),
    territory: z.string().optional().describe("Sales territory name."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ search, type, territory, limit }) => {
    const q = search?.toLowerCase();
    const rows = accounts.filter((a) => q ? `${a.name} ${a.city}`.toLowerCase().includes(q) : true).filter((a) => type ? a.type.toLowerCase() === type.toLowerCase() : true).filter((a) => territory ? a.territory.toLowerCase() === territory.toLowerCase() : true).slice(0, limit ?? 25);
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { count: rows.length, accounts: rows }
    };
  }
});

// src/lib/mcp/tools/list-contacts.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_contacts_default = defineTool3({
  name: "list_contacts",
  title: "List contacts",
  description: "List CRM contacts, optionally filtered by name, account name, or influence level.",
  inputSchema: {
    search: z2.string().optional().describe("Case-insensitive match on contact name, title, or email."),
    account_name: z2.string().optional().describe("Filter to contacts at this account."),
    influence_level: z2.enum(["High", "Medium", "Low"]).optional(),
    limit: z2.number().int().min(1).max(100).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ search, account_name, influence_level, limit }) => {
    const q = search?.toLowerCase();
    const acct = account_name?.toLowerCase();
    const rows = contacts.filter((c) => q ? `${c.name} ${c.title} ${c.email}`.toLowerCase().includes(q) : true).filter((c) => acct ? c.accountName.toLowerCase().includes(acct) : true).filter((c) => influence_level ? c.influenceLevel === influence_level : true).slice(0, limit ?? 25);
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { count: rows.length, contacts: rows }
    };
  }
});

// src/lib/mcp/tools/list-opportunities.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_opportunities_default = defineTool4({
  name: "list_opportunities",
  title: "List opportunities",
  description: "List pipeline opportunities with optional filters for stage, forecast status, manufacturer line, owner, and minimum value.",
  inputSchema: {
    stage: z3.string().optional().describe("Pipeline stage, e.g. Prospect, Specification, Bid, Awarded."),
    forecast_status: z3.enum(["Open", "Closed Won", "Closed Lost"]).optional(),
    manufacturer_line: z3.string().optional().describe("Manufacturer line name."),
    owner: z3.string().optional().describe("Opportunity owner / rep name."),
    min_value: z3.number().optional().describe("Only return opportunities worth at least this amount."),
    limit: z3.number().int().min(1).max(100).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ stage, forecast_status, manufacturer_line, owner, min_value, limit }) => {
    const rows = opportunities.filter((o) => stage ? o.stage.toLowerCase() === stage.toLowerCase() : true).filter((o) => forecast_status ? o.forecastStatus === forecast_status : true).filter(
      (o) => manufacturer_line ? o.manufacturerLine.toLowerCase().includes(manufacturer_line.toLowerCase()) : true
    ).filter((o) => owner ? o.owner.toLowerCase().includes(owner.toLowerCase()) : true).filter((o) => typeof min_value === "number" ? o.value >= min_value : true).sort((a, b) => b.value - a.value).slice(0, limit ?? 25);
    const totalValue = rows.reduce((sum, o) => sum + o.value, 0);
    return {
      content: [{ type: "text", text: JSON.stringify({ totalValue, rows }, null, 2) }],
      structuredContent: { count: rows.length, totalValue, opportunities: rows }
    };
  }
});

// src/lib/mcp/tools/list-orders.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z4 } from "npm:zod@^4.4.3";
var list_orders_default = defineTool5({
  name: "list_orders",
  title: "List orders",
  description: "List manufacturer orders with optional filters for status, fulfillment stage, account, or manufacturer line. Useful for checking what has shipped.",
  inputSchema: {
    status: z4.enum(["Pending", "Booked", "Shipped"]).optional(),
    order_stage: z4.string().optional().describe("Entered, Acknowledged, In Production, Shipped, Complete, Hold, Cancelled."),
    account_name: z4.string().optional(),
    manufacturer_line: z4.string().optional(),
    limit: z4.number().int().min(1).max(100).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ status, order_stage, account_name, manufacturer_line, limit }) => {
    const rows = orders.filter((o) => status ? o.status === status : true).filter((o) => order_stage ? o.orderStage.toLowerCase() === order_stage.toLowerCase() : true).filter(
      (o) => account_name ? o.accountName.toLowerCase().includes(account_name.toLowerCase()) : true
    ).filter(
      (o) => manufacturer_line ? o.manufacturerLine.toLowerCase().includes(manufacturer_line.toLowerCase()) : true
    ).slice(0, limit ?? 25);
    const totalValue = rows.reduce((sum, o) => sum + o.total, 0);
    return {
      content: [{ type: "text", text: JSON.stringify({ totalValue, rows }, null, 2) }],
      structuredContent: { count: rows.length, totalValue, orders: rows }
    };
  }
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z5 } from "npm:zod@^4.4.3";
var list_projects_default = defineTool6({
  name: "list_projects",
  title: "List projects",
  description: "List construction projects tracked in the CRM, with optional status, state, or name filters.",
  inputSchema: {
    search: z5.string().optional().describe("Case-insensitive match on project name, address, or architect."),
    status: z5.enum(["Pre-Design", "Design", "Bidding", "Complete"]).optional(),
    state: z5.string().optional().describe("Two-letter state code."),
    limit: z5.number().int().min(1).max(100).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ search, status, state, limit }) => {
    const q = search?.toLowerCase();
    const rows = projects.filter((p) => q ? `${p.name} ${p.address} ${p.architect}`.toLowerCase().includes(q) : true).filter((p) => status ? p.status === status : true).filter((p) => state ? p.state.toLowerCase() === state.toLowerCase() : true).slice(0, limit ?? 25);
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { count: rows.length, projects: rows }
    };
  }
});

// src/lib/mcp/tools/list-quotes.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z6 } from "npm:zod@^4.4.3";
var list_quotes_default = defineTool7({
  name: "list_quotes",
  title: "List quotes",
  description: "List quotes with optional filters for status, account, or manufacturer line.",
  inputSchema: {
    status: z6.string().optional().describe("Draft, Internal Review, Submitted, Revised, Accepted, Rejected, Expired."),
    account_name: z6.string().optional(),
    manufacturer_line: z6.string().optional(),
    limit: z6.number().int().min(1).max(100).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ status, account_name, manufacturer_line, limit }) => {
    const rows = quotes.filter((q) => status ? q.status.toLowerCase() === status.toLowerCase() : true).filter(
      (q) => account_name ? q.accountName.toLowerCase().includes(account_name.toLowerCase()) : true
    ).filter(
      (q) => manufacturer_line ? q.manufacturerLine.toLowerCase().includes(manufacturer_line.toLowerCase()) : true
    ).slice(0, limit ?? 25);
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { count: rows.length, quotes: rows }
    };
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z7 } from "npm:zod@^4.4.3";
var list_tasks_default = defineTool8({
  name: "list_tasks",
  title: "List tasks",
  description: "List follow-up tasks with optional filters for status, priority, or owner.",
  inputSchema: {
    status: z7.enum(["Open", "In Progress", "Complete"]).optional(),
    priority: z7.enum(["High", "Medium", "Low"]).optional(),
    owner: z7.string().optional(),
    limit: z7.number().int().min(1).max(100).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ status, priority, owner, limit }) => {
    const rows = tasks.filter((t) => status ? t.status === status : true).filter((t) => priority ? t.priority === priority : true).filter((t) => owner ? t.owner.toLowerCase().includes(owner.toLowerCase()) : true).slice(0, limit ?? 25);
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { count: rows.length, tasks: rows }
    };
  }
});

// src/lib/mcp/tools/pipeline-summary.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.25.0";
var pipeline_summary_default = defineTool9({
  name: "pipeline_summary",
  title: "Pipeline summary",
  description: "Return headline CRM metrics: pipeline value by stage, revenue by manufacturer line, forecast by rep, and dashboard totals.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const summary = { dashboardStats, pipelineByStage, revenueByLine, forecastByRep };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "aztputrohyqwzvlymalo";
var mcp_default = defineMcp({
  name: "repview-mcp",
  title: "Repview CRM",
  version: "0.1.0",
  instructions: "Tools for Repview, a building-envelope manufacturers' rep CRM. Use `pipeline_summary` for headline metrics, `list_opportunities` / `list_quotes` / `list_orders` for deal and fulfillment data, `list_accounts` / `list_contacts` / `list_projects` for relationship data, and `list_tasks` for follow-ups. `get_my_profile` returns the signed-in user's profile.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    pipeline_summary_default,
    list_accounts_default,
    list_contacts_default,
    list_opportunities_default,
    list_quotes_default,
    list_orders_default,
    list_projects_default,
    list_tasks_default,
    get_my_profile_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
